package com.namnp.heroes.presentation.constants

object WidgetIdentifier {
    const val SEARCH_WIDGET = "SEARCH_WIDGET"
    const val SEARCH_WIDGET_TEXT_FIELD = "SEARCH_WIDGET_TEXT_FIELD"
    const val SEARCH_WIDGET_CLOSE_BUTTON = "SEARCH_WIDGET_CLOSE_BUTTON"
    const val RATING_WIDGET_FILLED_STAR = "RATING_WIDGET_FILLED_STAR"
    const val RATING_WIDGET_HALF_FILLED_STAR = "RATING_WIDGET_HALF_FILLED_STAR"
    const val RATING_WIDGET_EMPTY_STAR = "RATING_WIDGET_EMPTY_STAR"
}

